In [21]:
from numpy.core.fromnumeric import reshape
import numpy as np 
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,51)
e=np.arange(10,52,2)
f=np.arange(9).reshape(3,3)
g=np.eye(3)
h=np.random.rand()
i=np.random.randn(25)
j=np.linspace(0.01,1,num=100)
j1=j.reshape(10,10)

mat = np.arange(1,26).reshape(5,5)
print(mat)
mat2=(mat[2:,1:])
mat3=(mat[3,-1])
mat4=(mat[0:3,1:2])
mat5=(mat[4:,0:6])
mat6=(mat[3:5,0:6])
mat_sum=np.sum(mat)
mat_std=np.std(mat)
mat_sum_axis=np.sum(mat,axis=0)
print(mat_sum_axis)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[55 60 65 70 75]
